# переменные заданы в файле .envversion: '3.7'
services:
  generator:
    build:
        context: services/tls
    image: generator
    volumes:
    - /services/tls:/keys :rw
  backend:
    build:
      context: services/backend
    image: backend
    volumes:
     - /services/tls:/tls  :ro
    ports:
      - 9999:9999
    links:
      - generator
      - auth
      - transactions
      - jaeger
  auth:
    build:
      context: services/auth
    image: auth
    ports:
      - 8080:8080
    volumes:
     - /services/tls:/tls  :ro
    links:
      - generator
      - jaeger
    environment:
      - APP_DSN=postgres://app:pass@authdb:5432/db
  authdb:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=db
    volumes:
      - ./services/auth/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
  transactions:
    build:
      context: services/transactions
    image: transactions
    ports:
      - 8888:8888
    volumes:
     - /services/tls:/tls :ro
    links:
      - generator
      - jaeger
    environment:
      - APP_DSN=postgres://app:pass@transactionsdb:5432/db
  transactionsdb:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=db
    volumes:
      - ./services/transactions/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
  jaeger:
    image: jaegertracing/all-in-one:1.20
    ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
        - "16686:16686"
